#!/usr/bin/env zsh

export ZSH_PLUGINS='/usr/local/share'

# VsCode / VSCodium
export VSCODE_EXTENSIONS=$XDG_DATA_HOME/vscode-oss/extensions

export HISTFILE=${XDG_CACHE_HOME}/zsh/zsh_history   # put history to cache, seperating it from the other ZDOT files

# aliases and functions
export FUNCS=$HOME/.local/functions

# zsh completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi

source $HOME/.config/machine/zshenv
