#!/usr/bin/env zsh

alias ls='ls --color=auto'
alias grep='rg'
alias ll='ls -la'

alias pmirror='sudo pacman-mirrors --fasttrack'
alias pup='sudo pacman -Syyu'
alias pi='sudo pacman -S --noconfirm'
alias yi='yay -S --noconfirm'

source $HOME/.config/machine/zshrc

