#!/bin/sh

# this script requires netcat to be installed

icon=""
essid=`iwgetid wlp3s0 --raw`
signal=`awk 'NR==3 {printf("%.0f%%",$3*10/7)}' /proc/net/wireless`
msg=""

check_connection() {
    # checking if we are connected to a wifi network
    if [ -z "$essid" ]; then
        icon=""
        essid="none"
        signal=""
        msg="| No WiFi network | "
    else
        # checking internet connection
        dunstify --replace=1 --timeout=1200 "Checking connection, please wait..."
        echo -e "GET http://www.google.com/ HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            icon=""
            msg="| Online | "
        else
            icon=""
            msg="| Offline | "
        fi
    fi
}

printf "%s %s" "$icon" "$signal" 

case $BUTTON in
    1) check_connection; dunstify --replace=1 "$essid $signal" "$msg Right click to open nmtui";;
    3) st -e nmtui & disown;;
esac
