#!/bin/bash

rofi_command="rofi -theme /usr/share/archcraft-dwm/rofi/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"
_msg="Options  -  yes / y / no / n"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime : $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
		systemctl poweroff
        ;;
    $reboot)
		systemctl reboot
        ;;
    $lock)
        slock
        ;;
    $suspend)
		mpc -q pause
		amixer set Master mute
		slock &
		systemctl suspend
        ;;
    $logout)
		pkill dwm
        ;;
esac

