#!/usr/bin/env zsh

####################################################################
# ZSH Config
####################################################################
# General Options
export CLICOLOR=1
setopt LOCAL_OPTIONS EXTENDED_GLOB
setopt AUTO_MENU ALWAYS_TO_END AUTO_LIST NO_MENU_COMPLETE COMPLETE_IN_WORD NOMATCH
unsetopt FLOW_CONTROL
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt inc_append_history
setopt share_history
setopt NOTIFY
setopt PROMPT_SUBST
setopt MULTIOS CDABLE_VARS
unsetopt correctall BEEP

HISTSIZE=50000
SAVEHIST=10000

# auto/tab completion 
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)    #include hidden files

# vim keys
bindkey -v
export KEYTIMEOUT=1

###############################################################################
# PROMPT
###############################################################################
eval "$(starship init zsh)"

alias k='clear'
alias kk='clear && reset'

alacritty_change_theme() {
    cat $HOME/.config/alacritty/base.yml > $HOME/.config/alacritty/alacritty.yml
    cat $1 >> $HOME/.config/alacritty/alacritty.yml
}
alias theme='ffs alacritty_change_theme $SRC/hub/alacritty-theme/themes'

ffs () {
    local result=`fd . "$2" -t f -H --ignore-file $XDG_CONFIG_HOME/.fdignore | fzf --reverse --height 40%`
    [ ! -z "$result" ] && $1 "$result"
}
alias dots='ffs nvim $XDG_CONFIG_HOME'
alias machine='ffs nvim $XDG_CONFIG_HOME/machine'
alias locs='ffs nvim $HOME/.local'

# aliases and functions
alias saf='search-alias-functions'
search-alias-functions(){
    echo '\e[1;34mNames\e[0m'
    print -l ${(ok)functions} | grep $1;
    echo '\e[1;34mAliases\e[0m'
    alias | grep $1;
}
expand-alias () {
  local POSSIBLE_ALIAS
  if [[ ! -z "$1" ]]; then
    POSSIBLE_ALIAS="$(alias $1)"
    if [[ ! -z "$POSSIBLE_ALIAS" ]]; then
      echo "${POSSIBLE_ALIAS#*=}"
    else
      echo "$1"
    fi
  fi
}

# file system
alias .....='cd ../../../../'
alias ....='cd ../../../'
alias ...='cd ../../'
alias ..='cd ..'

# git
alias git-to-main='git branch -m master main && git push -u origin main'
git-echo() { git pull origin master; git push echo master }
export GIT_LOG_PRETTY_FORMAT='%C(green)%h%C(auto)%d%C(reset) - %s | %C(cyan)%an %C(dim)%cr%C(reset)'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch -v'
alias gc='git clone'
alias gco='git checkout'
alias gd='git diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias gcm='git-commit'
alias gh='git-log-graph'
alias gl='git log'
alias gph='git push'
alias gpl='git pull'
alias gr='git remote -v'
alias gs='git status -sb --ignore-submodules'
alias gsync='git checkout master && git pull --rebase && git checkout - && git rebase master'
git-commit(){
    git commit -m ${1:-'Refactor'};
}
git-log-graph(){
    git log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10};
}
find-git-dirs () {
    find $1 -type d \( -exec test -d "{}/.git" -a "{}" != "." \; -print -prune -o -name .git -prune \)
}
exec-git-dirs () {
    local result=`find-git-dirs $2 | cut -d '/' -f5- | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden --reverse --height 40% | awk -v path="$2/" '{print path $0}'`
    [ ! -z "$result" ] && $1 $result
}
alias src='exec-git-dirs cd $SRC'

# dotfiles
dot () {
    git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
    }
alias da='dot add'
alias daa='dot add -u'
alias dcm='dot commit -m'
alias dh='dot-log-graph'
alias ddiff='dot diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias dl='dot ls-files'
alias dph='dot push'
alias dpl='dot pull'
alias ds='dot status -sb --ignore-submodules'
dot-log-graph() {
    dot log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10};
    }

# vscodium
alias c='code .'

# neo-vim
alias vim='nvim'
alias v='nvim'

# youtube-dl
alias y='youtube-dl'
alias ya='youtube-dl --extract-audio --audio-format m4a --audio-quality 0'

# doom emacs
alias doom="$HOME/.emacs.d/bin/doom"
doom-install(){
    git clone --depth 1 https://github.com/hlissner/doom-emacs $HOME/.emacs.d
    $HOME/.emacs.d/bin/doom install
}

