#!/usr/bin/env zsh

# NVim
export NVM_DIR=$HOME/.config/nvim
export NVIM_LOG_FILE=$HOME/.cache/nvim-log/

# Less
export LESSHISTFILE="-"

# only store unique commands in history
export HISTCONTROL=ignoreboth

# source code directory
export SRC=$HOME/src

export EDITOR=nvim
