#!/usr/bin/env zsh

alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
alias l.="ls -A | egrep '^\.'"
alias ll='ls -la --group-directories-first'
alias ls='ls --color=auto'
alias pacman='sudo pacman --color auto'
alias pi='sudo pacman -S --noconfirm'
alias update-fc='sudo fc-cache -fv'
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias update.="yay -Syu --noconfirm"
alias update='sudo pacman -Syyu'

# ex = EXtractor for all kinds of archives
# usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

source /usr/share/autojump/autojump.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $HOME/.config/machine/zshrc
