#!/usr/bin/env zsh
source $HOME/.config/os/zshenv

export ZSH_PLUGINS='/usr/local/share'
export TERM='xterm-256color'
export VSCODE_EXTENSIONS=$XDG_DATA_HOME/vscode-oss/extensions
export HISTFILE=${XDG_CACHE_HOME}/zsh/zsh_history   # put history to cache, seperating it from the other ZDOT files

source "$HOME/.cargo/env"
# zsh completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi
