#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "JetBrainsMono Nerd Font Mono:Regular:12.0"
spacebar -m config icon_font            "JetBrainsMono Nerd Font Mono:Regular:12.0"
spacebar -m config background_color     0xee202020
spacebar -m config foreground_color     0xffa8a8a8

#spacebar -m config display_separator                on
#spacebar -m config display_separator_icon           "|" 
#spacebar -m config display_separator_icon_color     0xffa8a8a8

spacebar -m config space_icon           "."
# spacebar -m config space_icon         "💻"
spacebar -m config space_icon_color     0xff458588
spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9

spacebar -m config clock_icon           " "
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config clock_format         "%Y-%m-%d %R"

spacebar -m config power_icon_strip     "🔋" "⚡"
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f

spacebar -m config dnd_icon             "*"
spacebar -m config dnd_icon_color       0xffa8a8a8

spacebar -m config right_shell          off
#spacebar -m config right_shell_icon     "☁️"
#spacebar -m config right_shell_command  "ansiweather -l ventura,us -u imperial -a false -p false -h false -w false -s false"

echo "spacebar configuration loaded.."

SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

echo "yabai configured for spacebar"
