#!/usr/bin/env zsh

####################################################################
# ZSH Config
####################################################################
# General Options
export CLICOLOR=1
setopt LOCAL_OPTIONS EXTENDED_GLOB
setopt AUTO_MENU ALWAYS_TO_END AUTO_LIST NO_MENU_COMPLETE COMPLETE_IN_WORD NOMATCH
unsetopt FLOW_CONTROL
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt inc_append_history
setopt share_history
setopt NOTIFY
setopt PROMPT_SUBST
setopt MULTIOS CDABLE_VARS
unsetopt correctall BEEP

HISTSIZE=50000
SAVEHIST=10000

# auto/tab completion 
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)    #include hidden files

###############################################################################
# PROMPT
###############################################################################
eval "$(starship init zsh)"

alacritty_change_theme() {
    ln -sfv "${1}" $HOME/.config/alacritty/theme.yml
}
dot () { git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"; }
dot-add-all(){
    dot add -u
    dot add $HOME/.config/os/*
}
dot-log-graph() { dot log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10}; }
exec-on-git-repos () {
    local result=`git-find-dirs $2 | cut -d '/' -f5- | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden --reverse --height 40% | awk -v path="$2/" '{print path $0}'`
    [ ! -z "$result" ] && $1 $result
}
exec-on-file () {
    local result=`fd . "$2" -t f -H --ignore-file $XDG_CONFIG_HOME/fdignore | fzf`
    [ ! -z "$result" ] && $1 "$result"
}
git-to-main() { git branch -m master main && git push -u origin main; }
git-commit(){ git commit -m ${1:-'Refactor'}; }
git-log-graph(){ git log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10}; }
git-find-dirs () { find $1 -type d \( -exec test -d "{}/.git" -a "{}" != "." \; -print -prune -o -name .git -prune \); }
search-alias-functions(){
    echo '\e[1;34mNames\e[0m'
    print -l ${(ok)functions} | grep $1;
    echo '\e[1;34mAliases\e[0m'
    alias | grep $1;
}
sshkey(){ ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com" -f $1; }
sshadd(){ eval "$(ssh-agent -s)" && ssh-add -K ~/.ssh/${1}; }

alias .....='cd ../../../../'
alias ....='cd ../../../'
alias ...='cd ../../'
alias ..='cd ..'
alias books='exec-on-file open $HOME/books/'
alias c='code .'
alias cb='cargo build'
alias cc='cargo check'
alias config='cd $XDG_CONFIG_HOME'
alias configs='nvim -c ":Files $XDG_CONFIG_HOME"'
alias da='dot add'
alias daa='dot-add-all'
alias dcm='dot commit -m'
alias ddiff='dot diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias dh='dot-log-graph'
alias dl='dot ls-files'
alias doom="$HOME/.emacs.d/bin/doom"
alias dph='dot push'
alias dpl='dot pull'
alias ds='dot status -sb --ignore-submodules'
alias g='lazygit'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch -v'
alias gc='git clone'
alias gcm='git-commit'
alias gco='git checkout'
alias gd='git diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias gh='git-log-graph'
alias gl='git log'
alias gph='git push'
alias gpl='git pull'
alias gr='git remote -vv'
alias gs='git status -sb --ignore-submodules'
alias gsync='git checkout master && git pull --rebase && git checkout - && git rebase master'
alias k='clear'
alias kk='clear && reset'
alias locals='nvim -c ":Files $HOME/.local"'
alias os='cd $XDG_CONFIG_HOME/os'
alias oss='nvim -c ":Files $XDG_CONFIG_HOME/os"'
alias repo='cd $HOME/src'
alias repos='exec-on-git-repos cd $SRC'
alias saf='search-alias-functions'
alias src='cd $HOME/src'
alias srcs='exec-on-git-repos cd $SRC'
alias srcg='exec-on-git-repos lazygit --path=$SRC'
alias theme='exec-on-file alacritty_change_theme $HOME/.local/themes/alacritty/'
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
alias up='topgrade' #'package-upgrade'
alias v='nvim'
alias vv='nvim -O'
alias vs='nvim -u $HOME/.Spacevim/init.vim'
alias vim='nvim'
alias y='youtube-dl'
alias ya='youtube-dl --extract-audio --audio-format m4a --audio-quality 0'

