[character]
success_symbol = "[ :](dimmed yellow)"
error_symbol = "[ :](red)"
vicmd_symbol = "[ ::](dimmed yellow)"

[prompt]
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$haskell\
$rust\
$nix_shell\
$line_break\
$jobs\
$time\
$cmd_duration\
$character\
"""

[aws]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 7
truncate_to_repo = true
style = "blue"

[git_branch]
symbol = ""
style = "cyan"

[nodejs]
disabled = true

[python]
disabled = true

[username]
disabled=false
format = "[$user](blue)@"

[hostname]
disabled=false
format = "[$hostname](red)"

[time]
disabled=false
format = "[$time](dimmed blue)"
