#!/bin/sh

CHOICE=$(echo -e "Laptop\nExternal\nDual" | dmenu \
    -c -cw 700 -l 20 -bw 5 \
    -fn "JetBrains Mono Light:size=14"\
    -nf "#c9d05c" -nb "#1d1d1d"\
    -sf "#c9d05c" -sb "#464632"\
    -nhf "#ffc24b" -nhb "#1d1d1d"\
    -shf "#ffc24b" -shb "#464632" \
    -p Monitor)

case "$CHOICE" in
	Laptop) xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off &;;
	External) xrandr --output eDP1 --off --output DP1 --off --output HDMI1 --primary --mode 3840x2160 --pos 1920x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off &;;
	Dual) xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --primary --mode 3840x2160 --pos 1920x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off &;;
esac
