#!/bin/sh

# This script checks if there are todos or appointments in 
# calcurse (a cli calendar application) and displays an icon
# accordingly in the statusbar. It also displays the number
# of todos and appointments in the form of a notification.

icon=""

todos=$(calcurse -t)
appointments=$(calcurse -a)

[ -n "$todos" ] && icon="" && num_t=$(echo "$todos" | wc -l) && let "num_t-=1" || num_t=0
[ -n "$appointments" ] && icon="" && num_a=$(echo "$appointments" | grep -v '^ - ' | wc -l) && let "num_a-=1" || num_a=0

echo "$icon"

showmsg() { 
    dunstify --replace=1 "$1" "$2"
}

[ -z "$BUTTON" ] && showmsg "Calcurse" "There are $num_t todos and $num_a appointments today"

case $BUTTON in
    1) showmsg "Todos: $num_t
Appointments: $num_a" "Right click to open calcurse";;
	3) st -f 'mono:pixelsize=20:antialias=true:autohint=true' -e calcurse && pkill -RTMIN+14 dwmblocks;;
esac
