#!/usr/bin/env zsh

# aliases and functions
export FUNCS=$HOME/.local/functions

# zsh completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi

# CJ
export EMPIRE_DEV_ACCT='845290112482'
export EMPIRE_PROD_ACCT='900394040587'
export CJDEV_DEV_ACCT='837465188358'
export CJDEV_PROD_ACCT='123972995618'
export COMM_DETAIL_PRD_ACCT='237555547766'
export AD_SYSTEMS_DEV_ACCT='157941295081'
export CJDBA_PROD_ACCT='095602282417'

export MAVEN_OPTS="-Xmx8G -Xss3m -XX:ReservedCodeCacheSize=256m"
export PROJECTS_DIR="$HOME/.local/cjdev"
export SOFTWARE_HOME="$PROJECTS_DIR"
export JAVA_HOME=`/usr/libexec/java_home -v 11`
export TNS_ADMIN="$SOFTWARE_HOME/ci/tns-admin/"
export DYLD_LIBRARY_PATH="$SOFTWARE_HOME/sqlplus/darwin"
export CLASSPATH="$SOFTWARE_HOME/bin:$CLASSPATH"
export DEVDB_HOST=devdb.db.cj.com
export DEVDB_USERNAME=spud
export DEVDB_PORT=1521
export DEVDB_SID=devdb

#export PATH="$PATH:$JAVA_HOME/bin"
#export PATH="$PATH:$SOFTWARE_HOME/resin"
#export PATH="$PATH:$SOFTWARE_HOME/bin"

export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

source $HOME/.config/os/macos/zshenv
