#!/usr/bin/env zsh

# base os config
source $HOME/.config/os/zshrc

# zsh plugins
source $ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh
source $ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/etc/profile.d/autojump.sh
#source $HOME/.fzf.zsh

green="$(tput setaf 2)"
reset="$(tput sgr0)"

brews() {
    local result=$(brew search --formulae | fzf -m --preview="brew info {}" --preview-window=:hidden --bind=space:toggle-preview)
    [ ! -z "$result" ] && brew install "$result"
}
casks() {
    local result=$(brew search --casks | fzf -m --preview="brew cask info {}" --preview-window=:hidden --bind=space:toggle-preview)
    [ ! -z "$result" ] && brew cask install "$result"
}
find-name(){
    # errors not displayed
    find "$1" -name "$2" -print 2>/dev/null
}
say(){ echo "${green}${1}${reset}"; }
stack-new(){ stack new $1 && cd $1 && stack setup && stack build; }
sha1c()  { shasum -a 1 -c "$1.sha1"; }
sha256c(){ shasum -a 256 -c "$1.sha256"; }
sha512c(){ shasum -a 512 -c "$1.sha512"; }
md5c()  { md5 -r "$1" | diff "$1.md5" -; }

alias bc="brew cask"
alias bi="brew info"
alias bl="brew leaves | xargs brew deps --installed --for-each | sed \"s/^.*:/$(tput setaf 4)&$(tput sgr0)/\""
alias bl="brew list && brew cask list && mas list"
alias bs="brew search"
alias bundle_name="osascript -e 'id of app"
alias caskroom="cd /usr/local/Caskroom && l"
alias cat='bat -p'
alias cellar="cd /usr/local/Cellar && l"
alias d='dirs -v | head -10'
alias dkl='docker ps -a'
alias dkr='docker run --rm'
alias dkrh='docker run --rm -d -p 8081:80'
alias dkrt='docker run --rm -it'
alias f='vifm'
alias grep='rg'
alias l='exa -1Fa --group-directories-first'
alias ll='exa --long --all --group-directories-first'
alias lt='exa --tree --level=2'
alias mc='k && java8 && mvn clean && java11'
alias mci='k && java8 && mvn clean install && java11'
alias mf="mas info"
alias mi="mas install"
alias ml="mas list"
alias mr="mas uninstall"
alias ms="mas search"
alias mup="mas upgrade"
alias sb='stack build'
alias sc='stack clean'
alias sg='ghcid --command "stack repl" --test ":main"'
alias sha1="shasum -a 1"
alias sha256="shasum -a 256"
alias sha512="shasum -a 512"
alias shopcart='sqlplus -L jwindsor@shopcart'
alias sinit='stack init'
alias sn='stack-new'
alias sr='stack repl'
alias st='stack test'
alias stt='stack ide targets'
alias sup='stack upgrade --force-download'
alias tree='exa --tree'
