#!/usr/bin/env zsh

# base os config
source $HOME/.config/os/zshrc

# zsh plugins
source $ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh
source $ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


alias cat='bat -p'
alias d='dirs -v | head -10'
alias f='vifm'
alias grep='rg'
alias ll='exa -lF --all --color=always --group-directories-first'
#alias ll='ls -laLhG'
alias lx='nnn -de'
alias tree='exa --tree'

# docker
alias dkl='docker ps -a'
alias dkr='docker run --rm'
alias dkrh='docker run --rm -d -p 8081:80'
alias dkrt='docker run --rm -it'

# haskell
stack-new(){ stack new $1 && cd $1 && stack setup && stack build; }
alias sb='stack build'
alias sc='stack clean'
alias sg='ghcid --command "stack repl" --test ":main"'
alias sinit='stack init'
alias sn='stack-new'
alias sr='stack repl'
alias st='stack test'
alias stt='stack ide targets'
alias sup='stack upgrade --force-download'

# macos
brews() {
    local result=$(brew formulae | fzf -m --preview="brew info {}" --preview-window=:hidden --bind=space:toggle-preview)
    [ ! -z "$result" ] && brew install "$result"
}
casks() {
    local result=$(brew search --casks | fzf -m --preview="brew cask info {}" --preview-window=:hidden --bind=space:toggle-preview)
    [ ! -z "$result" ] && brew cask install "$result"
}
sha1-check()  { shasum -a 1 -c "$1.sha1"; }
sha256-check(){ shasum -a 256 -c "$1.sha256"; }
sha512-check(){ shasum -a 512 -c "$1.sha512"; }
md5-check()  { md5 -r "$1" | diff "$1.md5" -; }
alias aws1="alias aws='/usr/local/opt/awscli@1/bin/aws'"
alias aws2="unalias aws"
alias bc="brew cask"
alias bi="brew info"
alias bl="brew leaves | xargs brew deps --installed --for-each | sed \"s/^.*:/$(tput setaf 4)&$(tput sgr0)/\""
alias bl="brew list && brew cask list && mas list"
alias bs="brew search"
alias bundle_name="osascript -e 'id of app"
alias caskroom="cd /usr/local/Caskroom && l"
alias cellar="cd /usr/local/Cellar && l"
alias m5c="md5-check"
alias mf="mas info"
alias mi="mas install"
alias ml="mas list"
alias mr="mas uninstall"
alias ms="mas search"
alias mup="mas upgrade"
alias s1="shasum -a 1"
alias s1c="sha1-check"
alias s2="shasum -a 256"
alias s2c="sha256-check"
alias s5="shasum -a 512"
alias s5c="sha512-check"
alias uber='cd Library/Application\ Support/Übersicht/widgets/'
