#!/bin/sh

# This script uses pactl to get the volume level and display it in
# the form of a notification and display an appropriate icon in the 
# status bar.

sinkinfo="$(pactl list sinks | grep 'Name\|Mute\|Volume:')"
vol=$(echo "$sinkinfo" | grep "front-left" | awk '{ print $5 }' | tr -d "%")
#icon=""
#echo "$sinkinfo" | grep "Mute: yes" > /dev/null && printf "%s %s%%" "$icon" "$vol" && exit
#
#if [ "$vol" -gt "100" ]; then
#    # Don't let the volume level exceed 100%.
#    # (0 is the index of the sink. Use pactl list sinks to get sink names.)
#    pactl set-sink-volume 0 100%
#    vol=100;
#	icon=""
#elif [ "$vol" -gt "70" ]; then
#	icon=""
#elif [ "$vol" -lt "30" ]; then
#	icon=""
#else
#	icon=""
#fi
printf "%s%%" "$vol"

#dunstify --replace=1 "Volume $vol%"

#case $BUTTON in
#    1) dunstify --replace=1 "Volume $vol%";;
#esac

